// packages/components/src/react/sidebar/sidebar-menu-item.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type SidebarMenuItemProps = ComponentPropsWithRef<"li">

export function SidebarMenuItem({ children, className, ...props }: SidebarMenuItemProps) {
  return (
    <li {...props} data-slot="sidebar-menu-item" className={cn("relative min-w-0", className)}>
      {children}
    </li>
  )
}

// generated/solid/sidebar/sidebar-menu-item.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type SidebarMenuItemProps = JSX.IntrinsicElements["li"]

export function SidebarMenuItem(props: SidebarMenuItemProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <li {...rest} data-slot="sidebar-menu-item" class={cn("relative min-w-0", local.class)}>
      {local.children}
    </li>
  )
}
