// generated/react/sidebar/sidebar-footer.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type SidebarFooterProps = ComponentPropsWithRef<"footer">

export function SidebarFooter({ children, className, ...props }: SidebarFooterProps) {
  return (
    <footer
      {...props}
      data-slot="sidebar-footer"
      className={cn("shrink-0 border-t border-border p-3", className)}
    >
      {children}
    </footer>
  )
}

// packages/components/src/solid/sidebar/sidebar-footer.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type SidebarFooterProps = JSX.IntrinsicElements["footer"]

export function SidebarFooter(props: SidebarFooterProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <footer
      {...rest}
      data-slot="sidebar-footer"
      class={cn("shrink-0 border-t border-border p-3", local.class)}
    >
      {local.children}
    </footer>
  )
}
