// packages/components/src/react/sidebar/sidebar-menu-button.react.tsx
import { interactiveRow } from "@/+css/interactive-row.css"
import { sidebarMenuControls } from "@/+css/sidebar.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithRef } from "react"

const $control = resolve(sidebarMenuControls)
const $interactiveRow = resolve(interactiveRow)

export type SidebarMenuButtonProps = ComponentPropsWithRef<"button">

export function SidebarMenuButton({
  children,
  className,
  type = "button",
  ...props
}: SidebarMenuButtonProps) {
  return (
    <button
      {...props}
      type={type}
      data-slot="sidebar-menu-button"
      className={cn($control("default"), $interactiveRow("default"), className)}
    >
      {children}
    </button>
  )
}

// packages/components/src/solid/sidebar/sidebar-menu-button.solid.tsx
import { interactiveRow } from "@/+css/interactive-row.css"
import { mergeProps, splitProps, type JSX } from "solid-js"
import { sidebarMenuControls } from "@/+css/sidebar.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $control = resolve(sidebarMenuControls)
const $interactiveRow = resolve(interactiveRow)

export type SidebarMenuButtonProps = JSX.IntrinsicElements["button"]

export function SidebarMenuButton(props: SidebarMenuButtonProps) {
  const [local, rest] = splitProps(mergeProps({ type: "button" } as const, props), [
    "children",
    "class",
    "type",
  ])

  return (
    <button
      {...rest}
      type={local.type}
      data-slot="sidebar-menu-button"
      class={cn($control("default"), $interactiveRow("default"), local.class)}
    >
      {local.children}
    </button>
  )
}
