// packages/components/src/react/sidebar/sidebar-menu.react.tsx
import { sidebarMenuLayout } from "@/+css/sidebar.css"
import { resolve } from "@hulla/ui"
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

const $menu = resolve(sidebarMenuLayout)

export type SidebarMenuProps = ComponentPropsWithRef<"ul"> & {
  /** Hierarchy lines for this branch. Defaults to nested; descendants may override. */
  lines?: "none" | "nested" | "all"
}

export function SidebarMenu({ children, className, lines, ...props }: SidebarMenuProps) {
  return (
    <ul
      {...props}
      data-slot="sidebar-menu"
      data-lines={lines}
      className={cn($menu("default"), className)}
    >
      {children}
    </ul>
  )
}

// packages/components/src/solid/sidebar/sidebar-menu.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { sidebarMenuLayout } from "@/+css/sidebar.css"
import { resolve } from "@hulla/ui"
import { cn } from "@/lib/style"

const $menu = resolve(sidebarMenuLayout)

export type SidebarMenuProps = JSX.IntrinsicElements["ul"] & {
  /** Hierarchy lines for this branch. Defaults to nested; descendants may override. */
  lines?: "none" | "nested" | "all"
}

export function SidebarMenu(props: SidebarMenuProps) {
  const [local, rest] = splitProps(props, ["children", "class", "lines"])

  return (
    <ul
      {...rest}
      data-slot="sidebar-menu"
      data-lines={local.lines}
      class={cn($menu("default"), local.class)}
    >
      {local.children}
    </ul>
  )
}
