// packages/components/src/react/sidebar/sidebar-menu-link.react.tsx
import { interactiveRow } from "@/+css/interactive-row.css"
import { sidebarMenuControls } from "@/+css/sidebar.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithRef } from "react"

const $control = resolve(sidebarMenuControls)
const $interactiveRow = resolve(interactiveRow)

export type SidebarMenuLinkProps = ComponentPropsWithRef<"a">

export function SidebarMenuLink({ children, className, ...props }: SidebarMenuLinkProps) {
  return (
    <a
      {...props}
      data-slot="sidebar-menu-link"
      className={cn($control("default"), $interactiveRow("default"), className)}
    >
      {children}
    </a>
  )
}

// packages/components/src/solid/sidebar/sidebar-menu-link.solid.tsx
import { interactiveRow } from "@/+css/interactive-row.css"
import { splitProps, type JSX } from "solid-js"
import { sidebarMenuControls } from "@/+css/sidebar.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $control = resolve(sidebarMenuControls)
const $interactiveRow = resolve(interactiveRow)

export type SidebarMenuLinkProps = JSX.IntrinsicElements["a"]

export function SidebarMenuLink(props: SidebarMenuLinkProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <a
      {...rest}
      data-slot="sidebar-menu-link"
      class={cn($control("default"), $interactiveRow("default"), local.class)}
    >
      {local.children}
    </a>
  )
}
