// generated/solid/combobox/combobox-group.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type ComboboxGroupProps = JSX.IntrinsicElements["div"]

export function ComboboxGroup(props: ComboboxGroupProps) {
  const [local, rest] = splitProps(mergeProps({ role: "group" } as const, props), [
    "children",
    "class",
    "role",
  ])

  return (
    <div
      {...rest}
      role={local.role}
      data-slot="combobox-group"
      class={cn("py-0 not-first:border-t not-first:border-border", local.class)}
    >
      {local.children}
    </div>
  )
}

// generated/react/combobox/combobox-group.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type ComboboxGroupProps = ComponentPropsWithRef<"div">

export function ComboboxGroup({
  children,
  className,
  role = "group",
  ...props
}: ComboboxGroupProps) {
  return (
    <div
      {...props}
      role={role}
      data-slot="combobox-group"
      className={cn(
        "py-0.5 not-first:border-t not-first:border-border not-first:pt-1.5",
        className
      )}
    >
      {children}
    </div>
  )
}
