// packages/components/src/react/table/table-row.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type TableRowProps = ComponentPropsWithRef<"tr">

export function TableRow({ children, className, ...props }: TableRowProps) {
  return (
    <tr
      {...props}
      data-slot="table-row"
      className={cn(
        "transition-colors hover:bg-foreground/[0.045] data-[state=selected]:bg-primary/10",
        className
      )}
    >
      {children}
    </tr>
  )
}

// packages/components/src/solid/table/table-row.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type TableRowProps = JSX.IntrinsicElements["tr"]

export function TableRow(props: TableRowProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <tr
      {...rest}
      data-slot="table-row"
      class={cn(
        "transition-colors hover:bg-foreground/[0.045] data-[state=selected]:bg-primary/10",
        local.class
      )}
    >
      {local.children}
    </tr>
  )
}
