// packages/components/src/react/table/table.react.tsx
import { tableVariants } from "@/+css/table.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithoutRef } from "react"

const $variant = resolve(tableVariants)

export type TableProps = ComponentPropsWithoutRef<"table"> & {
  variant?: typeof $variant.infer
}

export function Table({ children, className, variant = "divided", ...props }: TableProps) {
  return (
    <table
      {...props}
      data-slot="table"
      data-variant={variant}
      className={cn(
        "w-full border-separate border-spacing-0 text-left text-sm text-foreground",
        $variant(variant),
        className
      )}
    >
      {children}
    </table>
  )
}

// packages/components/src/solid/table/table.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { tableVariants } from "@/+css/table.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $variant = resolve(tableVariants)

export type TableProps = JSX.IntrinsicElements["table"] & {
  variant?: typeof $variant.infer
}

export function Table(props: TableProps) {
  const [local, rest] = splitProps(mergeProps({ variant: "divided" } as const, props), [
    "children",
    "class",
    "variant",
  ])

  return (
    <table
      {...rest}
      data-slot="table"
      data-variant={local.variant}
      class={cn(
        "w-full border-separate border-spacing-0 text-left text-sm text-foreground",
        $variant(local.variant),
        local.class
      )}
    >
      {local.children}
    </table>
  )
}
