// packages/components/src/react/file-upload/file-dropzone-title.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type FileDropzoneTitleProps = ComponentPropsWithRef<"span">

export function FileDropzoneTitle({ children, className, ...props }: FileDropzoneTitleProps) {
  return (
    <span
      {...props}
      data-slot="file-dropzone-title"
      className={cn("font-medium text-foreground", className)}
    >
      {children}
    </span>
  )
}

// packages/components/src/solid/file-upload/file-dropzone-title.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type FileDropzoneTitleProps = JSX.IntrinsicElements["span"]

export function FileDropzoneTitle(props: FileDropzoneTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="file-dropzone-title"
      class={cn("font-medium text-foreground", local.class)}
    >
      {local.children}
    </span>
  )
}
