// packages/components/src/react/file-upload/file-dropzone-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type FileDropzoneDescriptionProps = ComponentPropsWithRef<"span">

export function FileDropzoneDescription({
  children,
  className,
  ...props
}: FileDropzoneDescriptionProps) {
  return (
    <span
      {...props}
      data-slot="file-dropzone-description"
      className={cn("text-xs text-muted-foreground", className)}
    >
      {children}
    </span>
  )
}

// packages/components/src/solid/file-upload/file-dropzone-description.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type FileDropzoneDescriptionProps = JSX.IntrinsicElements["span"]

export function FileDropzoneDescription(props: FileDropzoneDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="file-dropzone-description"
      class={cn("text-xs text-muted-foreground", local.class)}
    >
      {local.children}
    </span>
  )
}
