// packages/components/src/solid/navigation-menu/navigation-menu-item.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type NavigationMenuItemProps = JSX.IntrinsicElements["li"] & {
  value?: string
}

export function NavigationMenuItem(props: NavigationMenuItemProps) {
  const [local, rest] = splitProps(props, ["children", "class", "value"])

  return (
    <li
      {...rest}
      data-slot="navigation-menu-item"
      data-state="closed"
      data-value={local.value}
      class={cn("contents", local.class)}
    >
      {local.children}
    </li>
  )
}

// packages/components/src/react/navigation-menu/navigation-menu-item.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type NavigationMenuItemProps = ComponentPropsWithRef<"li"> & {
  value?: string
}

export function NavigationMenuItem({
  children,
  className,
  value,
  ...props
}: NavigationMenuItemProps) {
  return (
    <li
      {...props}
      data-slot="navigation-menu-item"
      data-state="closed"
      data-value={value}
      className={cn("contents", className)}
    >
      {children}
    </li>
  )
}
