// generated/solid/code/code-block-title.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CodeBlockTitleProps = JSX.IntrinsicElements["div"]

export function CodeBlockTitle(props: CodeBlockTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div
      {...rest}
      data-slot="code-block-title"
      class={cn(
        "min-w-0 truncate font-mono text-xs font-medium tracking-[-0.01em] text-foreground",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}

// generated/react/code/code-block-title.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CodeBlockTitleProps = ComponentPropsWithRef<"div">

export function CodeBlockTitle({ children, className, ...props }: CodeBlockTitleProps) {
  return (
    <div
      {...props}
      data-slot="code-block-title"
      className={cn(
        "min-w-0 truncate font-mono text-xs font-medium tracking-[-0.01em] text-foreground",
        className
      )}
    >
      {children}
    </div>
  )
}
