// packages/components/src/solid/alert/alert-description.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type AlertDescriptionProps = JSX.IntrinsicElements["p"]

export function AlertDescription(props: AlertDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <p
      {...rest}
      data-slot="alert-description"
      class={cn("mt-1 text-muted-foreground", local.class)}
    >
      {local.children}
    </p>
  )
}

// generated/react/alert/alert-description.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithoutRef } from "react"

export type AlertDescriptionProps = ComponentPropsWithoutRef<"p">

export function AlertDescription({ children, className, ...props }: AlertDescriptionProps) {
  return (
    <p
      {...props}
      data-slot="alert-description"
      className={cn("mt-1 text-muted-foreground", className)}
    >
      {children}
    </p>
  )
}
