// packages/components/src/solid/combobox/combobox-content.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { popoverPlacements, popoverSurface } from "@/+css/popover.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $placement = resolve(popoverPlacements)
const $surface = resolve(popoverSurface)

export type ComboboxContentProps = JSX.IntrinsicElements["div"] & {
  placement?: typeof $placement.infer
}

export function ComboboxContent(props: ComboboxContentProps) {
  const [local, rest] = splitProps(
    mergeProps({ placement: "bottom-start", popover: "auto", role: "listbox" } as const, props),
    ["children", "class", "placement", "popover", "role"]
  )

  return (
    <div
      {...rest}
      popover={local.popover}
      role={local.role}
      data-placement={local.placement}
      data-slot="combobox-content"
      class={cn(
        $surface,
        $placement(local.placement),
        "min-w-[anchor-size(width)] max-w-[min(28rem,calc(100vw-1rem))] overscroll-contain p-1",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}

// packages/components/src/react/combobox/combobox-content.react.tsx
import { popoverPlacements, popoverSurface } from "@/+css/popover.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithRef } from "react"

const $placement = resolve(popoverPlacements)
const $surface = resolve(popoverSurface)

export type ComboboxContentProps = ComponentPropsWithRef<"div"> & {
  placement?: typeof $placement.infer
}

export function ComboboxContent({
  children,
  className,
  placement = "bottom-start",
  popover = "auto",
  role = "listbox",
  ...props
}: ComboboxContentProps) {
  return (
    <div
      {...props}
      popover={popover}
      role={role}
      data-placement={placement}
      data-slot="combobox-content"
      className={cn(
        $surface,
        $placement(placement),
        "min-w-[anchor-size(width)] max-w-[min(28rem,calc(100vw-1rem))] overscroll-contain p-0",
        className
      )}
    >
      {children}
    </div>
  )
}
