// generated/react/card/card-title.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CardTitleProps = ComponentPropsWithRef<"h3">

export function CardTitle({ children, className, ...props }: CardTitleProps) {
  return (
    <h3
      {...props}
      data-slot="card-title"
      className={cn("text-lg font-semibold leading-6 tracking-[-0.025em]", className)}
    >
      {children}
    </h3>
  )
}

// packages/components/src/solid/card/card-title.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CardTitleProps = JSX.IntrinsicElements["h3"]

export function CardTitle(props: CardTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <h3
      {...rest}
      data-slot="card-title"
      class={cn("text-lg font-semibold leading-6 tracking-[-0.025em]", local.class)}
    >
      {local.children}
    </h3>
  )
}
