// generated/react/breadcrumbs/breadcrumbs.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type BreadcrumbsProps = ComponentPropsWithRef<"nav">

export function Breadcrumbs({
  "aria-label": ariaLabel = "Breadcrumb",
  children,
  className,
  ...props
}: BreadcrumbsProps) {
  return (
    <nav
      {...props}
      aria-label={ariaLabel}
      data-slot="breadcrumbs"
      className={cn("min-w-0", className)}
    >
      <ol
        data-slot="breadcrumbs-list"
        className="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-sm leading-5 text-muted-foreground"
      >
        {children}
      </ol>
    </nav>
  )
}

// generated/solid/breadcrumbs/breadcrumbs.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type BreadcrumbsProps = JSX.IntrinsicElements["nav"]

export function Breadcrumbs(props: BreadcrumbsProps) {
  const [local, rest] = splitProps(mergeProps({ "aria-label": "Breadcrumb" } as const, props), [
    "aria-label",
    "children",
    "class",
  ])

  return (
    <nav
      {...rest}
      aria-label={local["aria-label"]}
      data-slot="breadcrumbs"
      class={cn("min-w-0", local.class)}
    >
      <ol
        data-slot="breadcrumbs-list"
        class="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-sm leading-5 text-muted-foreground"
      >
        {local.children}
      </ol>
    </nav>
  )
}
