// packages/components/src/solid/alert/alert-title.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type AlertTitleProps = JSX.IntrinsicElements["strong"]

export function AlertTitle(props: AlertTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <strong
      {...rest}
      data-slot="alert-title"
      class={cn("block font-semibold tracking-[-0.01em]", local.class)}
    >
      {local.children}
    </strong>
  )
}

// packages/components/src/react/alert/alert-title.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type AlertTitleProps = ComponentPropsWithRef<"strong">

export function AlertTitle({ children, className, ...props }: AlertTitleProps) {
  return (
    <strong
      {...props}
      data-slot="alert-title"
      className={cn("block font-semibold tracking-[-0.01em]", className)}
    >
      {children}
    </strong>
  )
}
