// packages/components/src/solid/field/field.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type FieldProps = Omit<JSX.IntrinsicElements["div"], "children"> & {
  children: JSX.Element
}

export function Field(props: FieldProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div
      {...rest}
      data-slot="field"
      class={cn(
        "group/field grid min-w-0 gap-1.5 text-left has-[:disabled]:opacity-70",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}

// generated/react/field/field.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef, ReactNode } from "react"

export type FieldProps = Omit<ComponentPropsWithRef<"div">, "children"> & {
  children: ReactNode
}

export function Field({ children, className, ...props }: FieldProps) {
  return (
    <div
      {...props}
      data-slot="field"
      className={cn(
        "group/field grid min-w-0 gap-1.5 text-left has-[:disabled]:opacity-70",
        className
      )}
    >
      {children}
    </div>
  )
}
