// generated/solid/field/field-description.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type FieldDescriptionProps = JSX.IntrinsicElements["p"]

export function FieldDescription(props: FieldDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <p
      {...rest}
      data-slot="description"
      class={cn("text-[0.8125rem] leading-5 text-muted-foreground", local.class)}
    >
      {local.children}
    </p>
  )
}

// generated/react/field/field-description.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithoutRef } from "react"

export type FieldDescriptionProps = ComponentPropsWithoutRef<"p">

export function FieldDescription({ children, className, ...props }: FieldDescriptionProps) {
  return (
    <p
      {...props}
      data-slot="description"
      className={cn("text-[0.8125rem] leading-5 text-muted-foreground", className)}
    >
      {children}
    </p>
  )
}
