// packages/components/src/react/table/table-container.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type TableContainerProps = ComponentPropsWithRef<"div">

export function TableContainer({ children, className, ...props }: TableContainerProps) {
  return (
    <div
      {...props}
      data-slot="table-container"
      className={cn(
        "min-w-0 overflow-x-auto rounded-md border border-border bg-surface",
        className
      )}
    >
      {children}
    </div>
  )
}

// generated/solid/table/table-container.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type TableContainerProps = JSX.IntrinsicElements["div"]

export function TableContainer(props: TableContainerProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <div
      {...rest}
      data-slot="table-container"
      class={cn("min-w-0 overflow-x-auto rounded-md border border-border bg-surface", local.class)}
    >
      {local.children}
    </div>
  )
}
