// generated/solid/command/command-group.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CommandGroupProps = JSX.IntrinsicElements["div"]

export function CommandGroup(props: CommandGroupProps) {
  const [local, rest] = splitProps(mergeProps({ role: "group" } as const, props), [
    "children",
    "class",
    "role",
  ])

  return (
    <div
      {...rest}
      role={local.role}
      data-slot="command-group"
      class={cn(
        "overflow-hidden p-1 text-foreground [&+&]:mt-1 [&+&]:border-t [&+&]:border-border [&+&]:pt-2",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}

// generated/react/command/command-group.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CommandGroupProps = ComponentPropsWithRef<"div">

export function CommandGroup({ children, className, role = "group", ...props }: CommandGroupProps) {
  return (
    <div
      {...props}
      role={role}
      data-slot="command-group"
      className={cn(
        "overflow-hidden py-0 text-foreground [&+&]:mt-1.5 [&+&]:border-t [&+&]:border-border [&+&]:pt-1.5",
        className
      )}
    >
      {children}
    </div>
  )
}
