// packages/components/src/react/card/card-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CardDescriptionProps = ComponentPropsWithRef<"p">

export function CardDescription({ children, className, ...props }: CardDescriptionProps) {
  return (
    <p
      {...props}
      data-slot="card-description"
      className={cn("text-sm leading-6 text-muted-foreground", className)}
    >
      {children}
    </p>
  )
}

// generated/solid/card/card-description.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CardDescriptionProps = JSX.IntrinsicElements["p"]

export function CardDescription(props: CardDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <p
      {...rest}
      data-slot="card-description"
      class={cn("text-sm leading-6 text-muted-foreground", local.class)}
    >
      {local.children}
    </p>
  )
}
