// packages/components/src/react/card/card-footer.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CardFooterProps = ComponentPropsWithRef<"footer">

export function CardFooter({ children, className, ...props }: CardFooterProps) {
  return (
    <footer
      {...props}
      data-slot="card-footer"
      className={cn(
        "mt-auto flex flex-wrap items-center gap-3 border-t border-border pt-5",
        className
      )}
    >
      {children}
    </footer>
  )
}

// generated/solid/card/card-footer.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CardFooterProps = JSX.IntrinsicElements["footer"]

export function CardFooter(props: CardFooterProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <footer
      {...rest}
      data-slot="card-footer"
      class={cn(
        "mt-auto flex flex-wrap items-center gap-3 border-t border-border pt-5",
        local.class
      )}
    >
      {local.children}
    </footer>
  )
}
