// generated/react/popover/popover-header.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type PopoverHeaderProps = ComponentPropsWithRef<"div">

export function PopoverHeader({ children, className, ...props }: PopoverHeaderProps) {
  return (
    <div
      {...props}
      data-slot="popover-header"
      className={cn("flex items-center gap-2.5 p-2.5", className)}
    >
      {children}
    </div>
  )
}

// packages/components/src/solid/popover/popover-header.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type PopoverHeaderProps = JSX.IntrinsicElements["div"]

export function PopoverHeader(props: PopoverHeaderProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <div
      {...rest}
      data-slot="popover-header"
      class={cn("flex items-center gap-2.5 p-2.5", local.class)}
    >
      {local.children}
    </div>
  )
}
