// packages/components/src/react/popover/popover.react.tsx
import { popoverPlacements, popoverSurface } from "@/+css/popover.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithoutRef } from "react"

const $placement = resolve(popoverPlacements)
const $surface = resolve(popoverSurface)

export type PopoverProps = ComponentPropsWithoutRef<"div"> & {
  placement?: typeof $placement.infer
}

export function Popover({
  children,
  className,
  placement = "bottom",
  popover = "auto",
  ...props
}: PopoverProps) {
  return (
    <div
      {...props}
      popover={popover}
      data-placement={placement}
      data-slot="popover"
      className={cn($surface, $placement(placement), className)}
    >
      {children}
    </div>
  )
}

// packages/components/src/solid/popover/popover.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { popoverPlacements, popoverSurface } from "@/+css/popover.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $placement = resolve(popoverPlacements)
const $surface = resolve(popoverSurface)

export type PopoverProps = JSX.IntrinsicElements["div"] & {
  placement?: typeof $placement.infer
}

export function Popover(props: PopoverProps) {
  const [local, rest] = splitProps(
    mergeProps({ placement: "bottom", popover: "auto" } as const, props),
    ["children", "class", "placement", "popover"]
  )

  return (
    <div
      {...rest}
      popover={local.popover}
      data-placement={local.placement}
      data-slot="popover"
      class={cn($surface, $placement(local.placement), local.class)}
    >
      {local.children}
    </div>
  )
}
