// examples/solid/src/components/menu/MenuList.tsx
/** @jsxImportSource solid-js */
import { cn } from '@/lib/style'
import type { JSX, ParentProps } from 'solid-js'

export type MenuListProps = ParentProps<JSX.MenuHTMLAttributes<HTMLMenuElement>>

export function MenuList({ children, ...props }: MenuListProps) {
  return (
    // @ts-expect-error issue in solid typedef: https://github.com/solidjs/solid/issues/2257
    <menu {...props} class={cn('space-y-sm w-full', props.class)}>
      {children}
    </menu>
  )
}

// generated/react/tailwind/menu/MenuList.tsx
import { cn } from '@/lib/style'
import type { DetailedHTMLProps, MenuHTMLAttributes, PropsWithChildren } from 'react'

type BaseProps = DetailedHTMLProps<MenuHTMLAttributes<HTMLMenuElement>, HTMLMenuElement>
export type MenuListProps = PropsWithChildren<BaseProps>

export function MenuList({ children, className, ...props }: MenuListProps) {
  return (
    <menu {...props} className={cn('space-y-sm w-full', className)}>
      {children}
    </menu>
  )
}
