// examples/solid/src/components/menu/Menu.tsx
/** @jsxImportSource solid-js **/
import { cn } from '@/lib/style'
import type { JSX, ParentProps } from 'solid-js'

export type MenuProps = ParentProps<JSX.DetailsHtmlAttributes<HTMLDetailsElement>>

export function Menu({ children, ...props }: MenuProps) {
  return (
    <details {...props} class={cn('group flex items-center', props.class)}>
      {children}
    </details>
  )
}

// generated/react/tailwind/menu/Menu.tsx
import { cn } from '@/lib/style'
import type { DetailedHTMLProps, DetailsHTMLAttributes, PropsWithChildren } from 'react'

type BaseProps = DetailedHTMLProps<DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>
export type MenuProps = PropsWithChildren<BaseProps>

export function Menu({ children, className, ...props }: MenuProps) {
  return (
    <details {...props} className={cn('group flex items-center', className)}>
      {children}
    </details>
  )
}
