// packages/components/src/react/popover/popover-title.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type PopoverTitleProps = ComponentPropsWithRef<"strong">

export function PopoverTitle({ children, className, ...props }: PopoverTitleProps) {
  return (
    <strong
      {...props}
      data-slot="popover-title"
      className={cn("block text-sm font-semibold", className)}
    >
      {children}
    </strong>
  )
}

// generated/solid/popover/popover-title.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type PopoverTitleProps = JSX.IntrinsicElements["strong"]

export function PopoverTitle(props: PopoverTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <strong
      {...rest}
      data-slot="popover-title"
      class={cn("block text-sm font-semibold", local.class)}
    >
      {local.children}
    </strong>
  )
}
