// packages/components/src/solid/table/table-body.solid.tsx
import { splitProps, type JSX } from "solid-js"

export type TableBodyProps = JSX.IntrinsicElements["tbody"]

export function TableBody(props: TableBodyProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <tbody {...rest} data-slot="table-body" class={local.class}>
      {local.children}
    </tbody>
  )
}

// generated/react/table/table-body.tsx
import type { ComponentPropsWithRef } from "react"

export type TableBodyProps = ComponentPropsWithRef<"tbody">

export function TableBody({ children, className, ...props }: TableBodyProps) {
  return (
    <tbody {...props} data-slot="table-body" className={className}>
      {children}
    </tbody>
  )
}
