// packages/components/src/solid/table/table-header.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type TableHeaderProps = JSX.IntrinsicElements["thead"]

export function TableHeader(props: TableHeaderProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <thead
      {...rest}
      data-slot="table-header"
      class={cn("[&_th]:border-b [&_th]:border-border", local.class)}
    >
      {local.children}
    </thead>
  )
}

// generated/react/table/table-header.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type TableHeaderProps = ComponentPropsWithRef<"thead">

export function TableHeader({ children, className, ...props }: TableHeaderProps) {
  return (
    <thead
      {...props}
      data-slot="table-header"
      className={cn("[&_th]:border-b [&_th]:border-border", className)}
    >
      {children}
    </thead>
  )
}
