// generated/solid/table/table-head.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type TableHeadProps = JSX.IntrinsicElements["th"]

export function TableHead(props: TableHeadProps) {
  const [local, rest] = splitProps(mergeProps({ scope: "col" } as const, props), [
    "children",
    "class",
    "scope",
  ])

  return (
    <th
      {...rest}
      scope={local.scope}
      data-slot="table-head"
      class={cn(
        "px-4 py-3 align-bottom text-xs font-medium tracking-wide text-muted-foreground",
        local.class
      )}
    >
      {local.children}
    </th>
  )
}

// packages/components/src/react/table/table-head.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type TableHeadProps = ComponentPropsWithRef<"th">

export function TableHead({ children, className, scope = "col", ...props }: TableHeadProps) {
  return (
    <th
      {...props}
      scope={scope}
      data-slot="table-head"
      className={cn(
        "px-4 py-3 align-bottom text-xs font-medium tracking-wide text-muted-foreground",
        className
      )}
    >
      {children}
    </th>
  )
}
