// generated/react/hover-card/hover-card-description.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type HoverCardDescriptionProps = ComponentPropsWithRef<"p">

export function HoverCardDescription({ children, className, ...props }: HoverCardDescriptionProps) {
  return (
    <p
      {...props}
      data-slot="hover-card-description"
      className={cn("m-0 text-xs leading-6 text-muted-foreground", className)}
    >
      {children}
    </p>
  )
}

// packages/components/src/solid/hover-card/hover-card-description.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type HoverCardDescriptionProps = JSX.IntrinsicElements["p"]

export function HoverCardDescription(props: HoverCardDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <p
      {...rest}
      data-slot="hover-card-description"
      class={cn("m-0 text-xs leading-6 text-muted-foreground", local.class)}
    >
      {local.children}
    </p>
  )
}
