// packages/components/src/react/navigation-menu/navigation-menu-link-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type NavigationMenuLinkDescriptionProps = ComponentPropsWithRef<"span">

export function NavigationMenuLinkDescription({
  children,
  className,
  ...props
}: NavigationMenuLinkDescriptionProps) {
  return (
    <span
      {...props}
      data-slot="navigation-menu-link-description"
      className={cn("text-xs leading-5 text-muted-foreground", className)}
    >
      {children}
    </span>
  )
}

// generated/solid/navigation-menu/navigation-menu-link-description.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type NavigationMenuLinkDescriptionProps = JSX.IntrinsicElements["span"]

export function NavigationMenuLinkDescription(props: NavigationMenuLinkDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="navigation-menu-link-description"
      class={cn("text-xs leading-5 text-muted-foreground", local.class)}
    >
      {local.children}
    </span>
  )
}
