// packages/components/src/react/navigation-menu/navigation-menu-link-title.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type NavigationMenuLinkTitleProps = ComponentPropsWithRef<"strong">

export function NavigationMenuLinkTitle({
  children,
  className,
  ...props
}: NavigationMenuLinkTitleProps) {
  return (
    <strong
      {...props}
      data-slot="navigation-menu-link-title"
      className={cn("text-sm font-medium tracking-[-0.015em]", className)}
    >
      {children}
    </strong>
  )
}

// generated/solid/navigation-menu/navigation-menu-link-title.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type NavigationMenuLinkTitleProps = JSX.IntrinsicElements["strong"]

export function NavigationMenuLinkTitle(props: NavigationMenuLinkTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <strong
      {...rest}
      data-slot="navigation-menu-link-title"
      class={cn("text-sm font-medium tracking-[-0.015em]", local.class)}
    >
      {local.children}
    </strong>
  )
}
