// generated/react/dropdown-menu/dropdown-menu-group.tsx
import type { ComponentPropsWithoutRef } from "react"

export type DropdownMenuGroupProps = ComponentPropsWithoutRef<"div">

export function DropdownMenuGroup({
  children,
  className,
  role = "group",
  ...props
}: DropdownMenuGroupProps) {
  return (
    <div {...props} role={role} data-slot="dropdown-menu-group" className={className}>
      {children}
    </div>
  )
}

// generated/solid/dropdown-menu/dropdown-menu-group.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"

export type DropdownMenuGroupProps = JSX.IntrinsicElements["div"]

export function DropdownMenuGroup(props: DropdownMenuGroupProps) {
  const [local, rest] = splitProps(mergeProps({ role: "group" } as const, props), [
    "children",
    "class",
    "role",
  ])

  return (
    <div {...rest} role={local.role} data-slot="dropdown-menu-group" class={local.class}>
      {local.children}
    </div>
  )
}
