// generated/react/tree-view/tree-view.tsx
import {
  connectTreeView,
  TREE_VIEW_EXPANDED_CHANGE_EVENT,
  TREE_VIEW_VALUE_CHANGE_EVENT,
  type TreeViewController,
  type TreeViewExpandedChangeDetail,
  type TreeViewSelectionMode,
  type TreeViewValueChangeDetail,
} from "@/lib/tree-view"
import { cn } from "@/lib/style"
import { useEffect, useImperativeHandle, useRef, type ComponentPropsWithRef } from "react"

export type TreeViewProps = Omit<ComponentPropsWithRef<"ul">, "defaultValue" | "onChange"> & {
  defaultValue?: string
  onExpandedChange?: (value: string, expanded: boolean) => void
  onValueChange?: (value: string) => void
  selectionMode?: TreeViewSelectionMode
  value?: string
}

export function TreeView({
  children,
  className,
  defaultValue,
  onExpandedChange,
  onValueChange,
  role = "tree",
  selectionMode = "single",
  value,
  ...props
}: TreeViewProps) {
  const elementRef = useRef<HTMLUListElement>(null)
  useImperativeHandle(props.ref, () => elementRef.current as HTMLUListElement, [])
  const controllerRef = useRef<TreeViewController>(null)
  const valueRef = useRef(value)
  const onExpandedChangeRef = useRef(onExpandedChange)
  const onValueChangeRef = useRef(onValueChange)
  valueRef.current = value
  onExpandedChangeRef.current = onExpandedChange
  onValueChangeRef.current = onValueChange

  useEffect(() => {
    const element = elementRef.current
    if (!element) return

    const controller = connectTreeView(element)
    controllerRef.current = controller

    const handleValueChange = (event: Event) => {
      const nextValue = (event as CustomEvent<TreeViewValueChangeDetail>).detail.value
      onValueChangeRef.current?.(nextValue)

      if (valueRef.current !== undefined) {
        queueMicrotask(() => controller.setValue(valueRef.current ?? ""))
      }
    }

    const handleExpandedChange = (event: Event) => {
      const detail = (event as CustomEvent<TreeViewExpandedChangeDetail>).detail
      onExpandedChangeRef.current?.(detail.value, detail.expanded)
    }

    element.addEventListener(TREE_VIEW_VALUE_CHANGE_EVENT, handleValueChange)
    element.addEventListener(TREE_VIEW_EXPANDED_CHANGE_EVENT, handleExpandedChange)

    return () => {
      element.removeEventListener(TREE_VIEW_VALUE_CHANGE_EVENT, handleValueChange)
      element.removeEventListener(TREE_VIEW_EXPANDED_CHANGE_EVENT, handleExpandedChange)
      controller.destroy()
      controllerRef.current = null
    }
  }, [])

  useEffect(() => {
    const controller = controllerRef.current
    if (!controller) return
    controller.refresh()
    if (value !== undefined) controller.setValue(value)
  }, [selectionMode, value])

  return (
    <ul
      {...props}
      ref={elementRef}
      role={role}
      data-initial-value={value ?? defaultValue}
      data-selection-mode={selectionMode}
      data-slot="tree-view"
      className={cn("m-0 grid min-w-0 list-none gap-0.5 p-0 text-foreground", className)}
    >
      {children}
    </ul>
  )
}

// generated/solid/tree-view/tree-view.tsx
import { createMutableRef, exposeRef, createLifecycleEffect, onMountEffect } from "@/lib/solid"
import { mergeProps, splitProps, type JSX } from "solid-js"
import {
  connectTreeView,
  TREE_VIEW_EXPANDED_CHANGE_EVENT,
  TREE_VIEW_VALUE_CHANGE_EVENT,
  type TreeViewController,
  type TreeViewExpandedChangeDetail,
  type TreeViewSelectionMode,
  type TreeViewValueChangeDetail,
} from "@/lib/tree-view"
import { cn } from "@/lib/style"

export type TreeViewProps = Omit<JSX.IntrinsicElements["ul"], "defaultValue" | "onChange"> & {
  defaultValue?: string
  onExpandedChange?: (value: string, expanded: boolean) => void
  onValueChange?: (value: string) => void
  selectionMode?: TreeViewSelectionMode
  value?: string
}

export function TreeView(props: TreeViewProps) {
  const [local, rest] = splitProps(
    mergeProps({ role: "tree", selectionMode: "single" } as const, props),
    [
      "children",
      "class",
      "defaultValue",
      "onExpandedChange",
      "onValueChange",
      "role",
      "selectionMode",
      "value",
    ]
  )

  const elementRef = createMutableRef<HTMLUListElement>(null)
  exposeRef(rest.ref, () => elementRef.current as HTMLUListElement, [])
  const controllerRef = createMutableRef<TreeViewController>(null)
  onMountEffect(() => {
    const element = elementRef.current
    if (!element) return

    const controller = connectTreeView(element)
    controllerRef.current = controller

    const handleValueChange = (event: Event) => {
      const nextValue = (event as CustomEvent<TreeViewValueChangeDetail>).detail.value
      local.onValueChange?.(nextValue)

      if (local.value !== undefined) {
        queueMicrotask(() => controller.setValue(local.value ?? ""))
      }
    }

    const handleExpandedChange = (event: Event) => {
      const detail = (event as CustomEvent<TreeViewExpandedChangeDetail>).detail
      local.onExpandedChange?.(detail.value, detail.expanded)
    }

    element.addEventListener(TREE_VIEW_VALUE_CHANGE_EVENT, handleValueChange)
    element.addEventListener(TREE_VIEW_EXPANDED_CHANGE_EVENT, handleExpandedChange)

    return () => {
      element.removeEventListener(TREE_VIEW_VALUE_CHANGE_EVENT, handleValueChange)
      element.removeEventListener(TREE_VIEW_EXPANDED_CHANGE_EVENT, handleExpandedChange)
      controller.destroy()
      controllerRef.current = null
    }
  })

  createLifecycleEffect(
    () => {
      const controller = controllerRef.current
      if (!controller) return
      controller.refresh()
      if (local.value !== undefined) controller.setValue(local.value)
    },
    () => [local.selectionMode, local.value]
  )

  return (
    <ul
      {...rest}
      ref={elementRef}
      role={local.role}
      data-initial-value={local.value ?? local.defaultValue}
      data-selection-mode={local.selectionMode}
      data-slot="tree-view"
      class={cn("m-0 grid min-w-0 list-none gap-0.5 p-0 text-foreground", local.class)}
    >
      {local.children}
    </ul>
  )
}
