// packages/components/src/solid/card/card-header.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CardHeaderProps = JSX.IntrinsicElements["header"]

export function CardHeader(props: CardHeaderProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <header {...rest} data-slot="card-header" class={cn("grid gap-1.5", local.class)}>
      {local.children}
    </header>
  )
}

// packages/components/src/react/card/card-header.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithoutRef } from "react"

export type CardHeaderProps = ComponentPropsWithoutRef<"header">

export function CardHeader({ children, className, ...props }: CardHeaderProps) {
  return (
    <header {...props} data-slot="card-header" className={cn("grid gap-1.5", className)}>
      {children}
    </header>
  )
}
