// packages/components/src/solid/card/card.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cardVariants } from "@/+css/card.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $variant = resolve(cardVariants)

export type CardProps = JSX.IntrinsicElements["article"] & {
  variant?: typeof $variant.infer
}

export function Card(props: CardProps) {
  const [local, rest] = splitProps(mergeProps({ variant: "outline" } as const, props), [
    "children",
    "class",
    "variant",
  ])

  return (
    <article
      {...rest}
      data-slot="card"
      data-variant={local.variant}
      class={cn(
        "group/card flex min-w-0 flex-col gap-6 rounded-lg border p-6 text-foreground",
        $variant(local.variant),
        local.class
      )}
    >
      {local.children}
    </article>
  )
}

// packages/components/src/react/card/card.react.tsx
import { cardVariants } from "@/+css/card.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithRef } from "react"

const $variant = resolve(cardVariants)

export type CardProps = ComponentPropsWithRef<"article"> & {
  variant?: typeof $variant.infer
}

export function Card({ children, className, variant = "outline", ...props }: CardProps) {
  return (
    <article
      {...props}
      data-slot="card"
      data-variant={variant}
      className={cn(
        "group/card flex min-w-0 flex-col gap-6 rounded-lg border p-6 text-foreground",
        $variant(variant),
        className
      )}
    >
      {children}
    </article>
  )
}
