// packages/components/src/react/input/input.react.tsx
import { formControlSizes, formControlVariants } from "@/+css/form-control.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithoutRef } from "react"

const $size = resolve(formControlSizes)
const $variant = resolve(formControlVariants)

export type InputProps = ComponentPropsWithoutRef<"input"> & {
  controlSize?: typeof $size.infer
  variant?: typeof $variant.infer
}

export function Input({
  className,
  controlSize = "md",
  variant = "outline",
  ...props
}: InputProps) {
  return (
    <input
      {...props}
      data-slot="control"
      className={cn(
        "block w-full min-w-0 appearance-none text-foreground antialiased placeholder:text-muted-foreground/65 transition-[background-color,border-color,box-shadow,color] duration-150 ease-out motion-reduce:transition-none file:mr-3 file:border-0 file:bg-transparent file:p-0 file:font-medium file:leading-[inherit] file:text-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-55 read-only:cursor-default aria-invalid:placeholder:text-danger/60",
        $size(controlSize),
        $variant(variant),
        className
      )}
    />
  )
}

// packages/components/src/solid/input/input.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { formControlSizes, formControlVariants } from "@/+css/form-control.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $size = resolve(formControlSizes)
const $variant = resolve(formControlVariants)

export type InputProps = JSX.IntrinsicElements["input"] & {
  controlSize?: typeof $size.infer
  variant?: typeof $variant.infer
}

export function Input(props: InputProps) {
  const [local, rest] = splitProps(
    mergeProps({ controlSize: "md", variant: "outline" } as const, props),
    ["class", "controlSize", "variant"]
  )

  return (
    <input
      {...rest}
      data-control=""
      data-slot="control"
      class={cn(
        "block w-full min-w-0 appearance-none text-foreground antialiased placeholder:text-muted-foreground/65 transition-[background-color,border-color,box-shadow,color] duration-150 ease-out motion-reduce:transition-none file:mr-3 file:border-0 file:bg-transparent file:p-0 file:font-medium file:leading-[inherit] file:text-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-55 read-only:cursor-default aria-invalid:placeholder:text-danger/60",
        $size(local.controlSize),
        $variant(local.variant),
        local.class
      )}
    />
  )
}
