// generated/solid/sidebar/sidebar-group.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type SidebarGroupProps = JSX.IntrinsicElements["section"]

export function SidebarGroup(props: SidebarGroupProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <section {...rest} data-slot="sidebar-group" class={cn("min-w-0 py-1.5", local.class)}>
      {local.children}
    </section>
  )
}

// generated/react/sidebar/sidebar-group.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type SidebarGroupProps = ComponentPropsWithRef<"section">

export function SidebarGroup({ children, className, ...props }: SidebarGroupProps) {
  return (
    <section {...props} data-slot="sidebar-group" className={cn("min-w-0 py-1.5", className)}>
      {children}
    </section>
  )
}
