// packages/components/src/react/field/field-content.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type FieldContentProps = ComponentPropsWithRef<"div">

export function FieldContent({ children, className, ...props }: FieldContentProps) {
  return (
    <div {...props} data-slot="field-content" className={cn("grid min-w-0 gap-0.5", className)}>
      {children}
    </div>
  )
}

// packages/components/src/solid/field/field-content.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type FieldContentProps = JSX.IntrinsicElements["div"]

export function FieldContent(props: FieldContentProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <div {...rest} data-slot="field-content" class={cn("grid min-w-0 gap-0.5", local.class)}>
      {local.children}
    </div>
  )
}
