// packages/components/src/react/hover-card/hover-card-title.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type HoverCardTitleProps = ComponentPropsWithRef<"strong">

export function HoverCardTitle({ children, className, ...props }: HoverCardTitleProps) {
  return (
    <strong
      {...props}
      data-slot="hover-card-title"
      className={cn("block text-base font-semibold", className)}
    >
      {children}
    </strong>
  )
}

// generated/solid/hover-card/hover-card-title.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type HoverCardTitleProps = JSX.IntrinsicElements["strong"]

export function HoverCardTitle(props: HoverCardTitleProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <strong
      {...rest}
      data-slot="hover-card-title"
      class={cn("block text-base font-semibold", local.class)}
    >
      {local.children}
    </strong>
  )
}
