// generated/react/command/command-empty.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CommandEmptyProps = ComponentPropsWithRef<"div">

export function CommandEmpty({
  children,
  className,
  hidden = true,
  role = "status",
  ...props
}: CommandEmptyProps) {
  return (
    <div
      {...props}
      hidden={hidden}
      role={role}
      data-slot="command-empty"
      className={cn("px-4 py-10 text-center text-sm text-muted-foreground", className)}
    >
      {children}
    </div>
  )
}

// generated/solid/command/command-empty.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CommandEmptyProps = JSX.IntrinsicElements["div"]

export function CommandEmpty(props: CommandEmptyProps) {
  const [local, rest] = splitProps(mergeProps({ hidden: true, role: "status" } as const, props), [
    "children",
    "class",
    "hidden",
    "role",
  ])

  return (
    <div
      {...rest}
      hidden={local.hidden}
      role={local.role}
      data-slot="command-empty"
      class={cn("px-4 py-10 text-center text-sm text-muted-foreground", local.class)}
    >
      {local.children}
    </div>
  )
}
