// generated/react/command/command-separator.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CommandSeparatorProps = ComponentPropsWithRef<"hr">

export function CommandSeparator({ className, ...props }: CommandSeparatorProps) {
  return (
    <hr
      {...props}
      data-slot="command-separator"
      className={cn("mx-0 my-1.5 h-px border-0 bg-border", className)}
    />
  )
}

// generated/solid/command/command-separator.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CommandSeparatorProps = JSX.IntrinsicElements["hr"]

export function CommandSeparator(props: CommandSeparatorProps) {
  const [local, rest] = splitProps(props, ["class"])

  return (
    <hr
      {...rest}
      data-slot="command-separator"
      class={cn("-mx-1 my-1 h-px border-0 bg-border", local.class)}
    />
  )
}
