// packages/components/src/solid/breadcrumbs/breadcrumb-ellipsis.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type BreadcrumbEllipsisProps = JSX.IntrinsicElements["span"]

export function BreadcrumbEllipsis(props: BreadcrumbEllipsisProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="breadcrumb-ellipsis"
      class={cn("inline-flex font-mono tracking-[0.12em]", local.class)}
    >
      {local.children ?? (
        <>
          <span aria-hidden="true">···</span>
          <span class="sr-only">More pages</span>
        </>
      )}
    </span>
  )
}

// packages/components/src/react/breadcrumbs/breadcrumb-ellipsis.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type BreadcrumbEllipsisProps = ComponentPropsWithRef<"span">

export function BreadcrumbEllipsis({ children, className, ...props }: BreadcrumbEllipsisProps) {
  return (
    <span
      {...props}
      data-slot="breadcrumb-ellipsis"
      className={cn("inline-flex font-mono tracking-[0.12em]", className)}
    >
      {children ?? (
        <>
          <span aria-hidden="true">···</span>
          <span className="sr-only">More pages</span>
        </>
      )}
    </span>
  )
}
