// generated/solid/select/select-group-label.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type SelectGroupLabelProps = JSX.IntrinsicElements["div"]

export function SelectGroupLabel(props: SelectGroupLabelProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div
      {...rest}
      data-slot="select-group-label"
      class={cn(
        "px-3 pt-2 pb-1 font-mono text-[0.625rem] font-medium tracking-[0.08em] text-muted-foreground uppercase",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}

// generated/react/select/select-group-label.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type SelectGroupLabelProps = ComponentPropsWithRef<"div">

export function SelectGroupLabel({ children, className, ...props }: SelectGroupLabelProps) {
  return (
    <div
      {...props}
      data-slot="select-group-label"
      className={cn(
        "px-3 pt-2 pb-1 font-mono text-[0.625rem] font-medium tracking-[0.08em] text-muted-foreground uppercase",
        className
      )}
    >
      {children}
    </div>
  )
}
