// packages/components/src/solid/card/card-content.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CardContentProps = JSX.IntrinsicElements["div"]

export function CardContent(props: CardContentProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div {...rest} data-slot="card-content" class={cn("min-w-0", local.class)}>
      {local.children}
    </div>
  )
}

// generated/react/card/card-content.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CardContentProps = ComponentPropsWithRef<"div">

export function CardContent({ children, className, ...props }: CardContentProps) {
  return (
    <div {...props} data-slot="card-content" className={cn("min-w-0", className)}>
      {children}
    </div>
  )
}
