// packages/components/src/react/code/code-block.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CodeBlockProps = ComponentPropsWithRef<"div">

export function CodeBlock({ children, className, ...props }: CodeBlockProps) {
  return (
    <div
      {...props}
      data-slot="code-block"
      className={cn(
        "group/code-block min-w-0 overflow-hidden rounded-md border border-border bg-surface-raised text-foreground shadow-sm",
        className
      )}
    >
      {children}
    </div>
  )
}

// packages/components/src/solid/code/code-block.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CodeBlockProps = JSX.IntrinsicElements["div"]

export function CodeBlock(props: CodeBlockProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div
      {...rest}
      data-slot="code-block"
      class={cn(
        "group/code-block min-w-0 overflow-hidden rounded-md border border-border bg-surface-raised text-foreground shadow-sm",
        local.class
      )}
    >
      {local.children}
    </div>
  )
}
