// packages/components/src/react/code/code-block-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type CodeBlockDescriptionProps = ComponentPropsWithRef<"div">

export function CodeBlockDescription({ children, className, ...props }: CodeBlockDescriptionProps) {
  return (
    <div
      {...props}
      data-slot="code-block-description"
      className={cn("min-w-0 text-xs leading-5 text-muted-foreground", className)}
    >
      {children}
    </div>
  )
}

// packages/components/src/solid/code/code-block-description.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type CodeBlockDescriptionProps = JSX.IntrinsicElements["div"]

export function CodeBlockDescription(props: CodeBlockDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div
      {...rest}
      data-slot="code-block-description"
      class={cn("min-w-0 text-xs leading-5 text-muted-foreground", local.class)}
    >
      {local.children}
    </div>
  )
}
