// generated/react/stepper/stepper.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type StepperProps = ComponentPropsWithRef<"ol"> & { orientation?: "horizontal" | "vertical" }

export function Stepper({
  children,
  className,
  orientation = "horizontal",
  ...props
}: StepperProps) {
  return (
    <ol
      {...props}
      data-orientation={orientation}
      role="list"
      data-slot="stepper"
      className={cn(
        "group/stepper m-0 flex w-full min-w-0 list-none gap-5 p-0 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-4",
        className
      )}
    >
      {children}
    </ol>
  )
}

// packages/components/src/solid/stepper/stepper.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type StepperProps = JSX.IntrinsicElements["ol"] & { orientation?: "horizontal" | "vertical" }

export function Stepper(props: StepperProps) {
  const [local, rest] = splitProps(props, ["children", "class", "orientation"])
  return (
    <ol
      {...rest}
      data-orientation={local.orientation ?? "horizontal"}
      role="list"
      data-slot="stepper"
      class={cn(
        "group/stepper m-0 flex w-full min-w-0 list-none gap-5 p-0 data-[orientation=vertical]:flex-col data-[orientation=vertical]:gap-4",
        local.class
      )}
    >
      {local.children}
    </ol>
  )
}
