// packages/components/src/react/stepper/stepper-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type StepperDescriptionProps = ComponentPropsWithRef<"span">

export function StepperDescription({ children, className, ...props }: StepperDescriptionProps) {
  return (
    <span
      {...props}
      data-slot="stepper-description"
      className={cn("text-xs font-normal leading-4 text-muted-foreground", className)}
    >
      {children}
    </span>
  )
}

// packages/components/src/solid/stepper/stepper-description.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type StepperDescriptionProps = JSX.IntrinsicElements["span"]

export function StepperDescription(props: StepperDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="stepper-description"
      class={cn("text-xs font-normal leading-4 text-muted-foreground", local.class)}
    >
      {local.children}
    </span>
  )
}
