// packages/components/src/react/navigation-menu/navigation-menu-link-content.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type NavigationMenuLinkContentProps = ComponentPropsWithRef<"span">

export function NavigationMenuLinkContent({
  children,
  className,
  ...props
}: NavigationMenuLinkContentProps) {
  return (
    <span
      {...props}
      data-slot="navigation-menu-link-content"
      className={cn("grid min-w-0 gap-0.5", className)}
    >
      {children}
    </span>
  )
}

// packages/components/src/solid/navigation-menu/navigation-menu-link-content.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type NavigationMenuLinkContentProps = JSX.IntrinsicElements["span"]

export function NavigationMenuLinkContent(props: NavigationMenuLinkContentProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span
      {...rest}
      data-slot="navigation-menu-link-content"
      class={cn("grid min-w-0 gap-0.5", local.class)}
    >
      {local.children}
    </span>
  )
}
