// packages/components/src/solid/select/select-value.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type SelectValueProps = JSX.IntrinsicElements["span"] & {
  placeholder?: string
}

export function SelectValue(props: SelectValueProps) {
  const [local, rest] = splitProps(mergeProps({ placeholder: "" } as const, props), [
    "children",
    "class",
    "placeholder",
  ])

  return (
    <span
      {...rest}
      data-placeholder={local.placeholder}
      data-slot="select-value"
      class={cn(
        "min-w-0 flex-1 truncate data-[state=placeholder]:text-muted-foreground",
        local.class
      )}
    >
      {local.children ?? local.placeholder}
    </span>
  )
}

// packages/components/src/react/select/select-value.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type SelectValueProps = ComponentPropsWithRef<"span"> & {
  placeholder?: string
}

export function SelectValue({ children, className, placeholder = "", ...props }: SelectValueProps) {
  return (
    <span
      {...props}
      data-placeholder={placeholder}
      data-slot="select-value"
      className={cn(
        "min-w-0 flex-1 truncate data-[state=placeholder]:text-muted-foreground",
        className
      )}
    >
      {children ?? placeholder}
    </span>
  )
}
