// packages/ui/src/menu/react/Menu.react.tsx
import { cn } from '@/lib/style'
import type { DetailedHTMLProps, DetailsHTMLAttributes, PropsWithChildren } from 'react'
import { menu } from '../style/tailwind.menu'

type BaseProps = DetailedHTMLProps<DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>
export type MenuProps = PropsWithChildren<BaseProps>

export function Menu({ children, className, ...props }: MenuProps) {
  return (
    <details {...props} className={cn(menu, className)}>
      {children}
    </details>
  )
}

// packages/ui/src/menu/solid/Menu.solid.tsx
/** @jsxImportSource solid-js **/
import { cn } from '@/lib/style'
import type { JSX, ParentProps } from 'solid-js'
import { menu } from '../style/tailwind.menu'

export type MenuProps = ParentProps<JSX.DetailsHtmlAttributes<HTMLDetailsElement>>

export function Menu({ children, ...props }: MenuProps) {
  return (
    <details {...props} class={cn(menu, props.class)}>
      {children}
    </details>
  )
}
