// packages/ui/src/menu/react/MenuItem.react.tsx
import { cn } from '@/lib/style'
import type { DetailedHTMLProps, LiHTMLAttributes, PropsWithChildren } from 'react'
import { menuitem } from '../style/tailwind.menu'

type BaseProps = DetailedHTMLProps<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>
export type MenuItemProps = PropsWithChildren<
  BaseProps & {
    active?: boolean
    nested?: boolean
  }
>

export function MenuItem({ children, className, ...props }: MenuItemProps) {
  return (
    <li {...props} data-active={props.active} data-nested={props.nested} className={cn(menuitem, className)}>
      {children}
    </li>
  )
}

// packages/ui/src/menu/solid/MenuItem.solid.tsx
/** @jsxImportSource solid-js */
import { cn } from '@/lib/style'
import type { JSX, ParentProps } from 'solid-js'
import { menuitem } from '../style/tailwind.menu'

export type MenuItemProps = ParentProps<
  JSX.DetailsHtmlAttributes<HTMLLIElement> & {
    active?: boolean
    nested?: boolean
  }
>

export function MenuItem({ children, ...props }: MenuItemProps) {
  return (
    <li {...props} data-active={props.active} data-nested={props.nested} class={cn(menuitem, props.class)}>
      {children}
    </li>
  )
}
