// packages/components/src/solid/badge/badge.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { badgeSizes, badgeVariants } from "@/+css/badge.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"

const $size = resolve(badgeSizes)
const $variant = resolve(badgeVariants)

export type BadgeProps = JSX.IntrinsicElements["span"] & {
  size?: typeof $size.infer
  variant?: typeof $variant.infer
}

export function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(mergeProps({ size: "md", variant: "neutral" } as const, props), [
    "children",
    "class",
    "size",
    "variant",
  ])

  return (
    <span
      {...rest}
      data-slot="badge"
      class={cn(
        "inline-flex shrink-0 items-center justify-center whitespace-nowrap border font-medium leading-none tracking-[0.01em] antialiased [&>svg]:shrink-0",
        $variant(local.variant),
        $size(local.size),
        local.class
      )}
    >
      {local.children}
    </span>
  )
}

// packages/components/src/react/badge/badge.react.tsx
import { badgeSizes, badgeVariants } from "@/+css/badge.css"
import { cn } from "@/lib/style"
import { resolve } from "@hulla/ui"
import type { ComponentPropsWithoutRef } from "react"

const $size = resolve(badgeSizes)
const $variant = resolve(badgeVariants)

export type BadgeProps = ComponentPropsWithoutRef<"span"> & {
  size?: typeof $size.infer
  variant?: typeof $variant.infer
}

export function Badge({
  children,
  className,
  size = "md",
  variant = "neutral",
  ...props
}: BadgeProps) {
  return (
    <span
      {...props}
      data-slot="badge"
      className={cn(
        "inline-flex shrink-0 items-center justify-center whitespace-nowrap border font-medium leading-none tracking-[0.01em] antialiased [&>svg]:shrink-0",
        $variant(variant),
        $size(size),
        className
      )}
    >
      {children}
    </span>
  )
}
