// packages/components/src/solid/tag-input/tag-input-label.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type TagInputLabelProps = JSX.IntrinsicElements["span"]

export function TagInputLabel(props: TagInputLabelProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <span {...rest} data-slot="tag-input-label" class={cn("min-w-0 truncate", local.class)}>
      {local.children}
    </span>
  )
}

// generated/react/tag-input/tag-input-label.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type TagInputLabelProps = ComponentPropsWithRef<"span">

export function TagInputLabel({ children, className, ...props }: TagInputLabelProps) {
  return (
    <span {...props} data-slot="tag-input-label" className={cn("min-w-0 truncate", className)}>
      {children}
    </span>
  )
}
