// packages/components/src/solid/radio/radio-group.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type RadioGroupProps = Omit<JSX.IntrinsicElements["fieldset"], "children"> & {
  children: JSX.Element
}

export function RadioGroup(props: RadioGroupProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <fieldset
      {...rest}
      data-slot="radio-group"
      class={cn("m-0 grid min-w-0 gap-3 border-0 p-0 text-left", local.class)}
    >
      {local.children}
    </fieldset>
  )
}

// packages/components/src/react/radio/radio-group.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef, ReactNode } from "react"

export type RadioGroupProps = Omit<ComponentPropsWithRef<"fieldset">, "children"> & {
  children: ReactNode
}

export function RadioGroup({ children, className, ...props }: RadioGroupProps) {
  return (
    <fieldset
      {...props}
      data-slot="radio-group"
      className={cn("m-0 grid min-w-0 gap-3 border-0 p-0 text-left", className)}
    >
      {children}
    </fieldset>
  )
}
