// packages/components/src/solid/radio/radio.solid.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type RadioProps = Omit<JSX.IntrinsicElements["input"], "type">

export function Radio(props: RadioProps) {
  const [local, rest] = splitProps(props, ["class"])

  return (
    <input
      {...rest}
      type="radio"
      data-slot="radio"
      class={cn(
        "relative inline-grid size-[1.125rem] shrink-0 appearance-none place-content-center rounded-full border border-border bg-surface align-middle shadow-xs transition-[background-color,border-color,box-shadow] duration-150 ease-out before:size-2 before:scale-50 before:rounded-full before:bg-primary-foreground before:opacity-0 before:transition-[opacity,transform] before:duration-100 before:ease-out before:content-[''] checked:border-primary checked:bg-primary checked:before:scale-100 checked:before:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none motion-reduce:transition-none motion-reduce:before:transition-none dark:bg-foreground/[0.1] dark:checked:bg-primary aria-invalid:border-danger aria-invalid:checked:bg-danger aria-invalid:focus-visible:outline-danger dark:aria-invalid:checked:bg-danger",
        local.class
      )}
    />
  )
}

// packages/components/src/react/radio/radio.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type RadioProps = Omit<ComponentPropsWithRef<"input">, "type">

export function Radio({ className, ...props }: RadioProps) {
  return (
    <input
      {...props}
      type="radio"
      data-slot="radio"
      className={cn(
        "relative inline-grid size-[1.125rem] shrink-0 appearance-none place-content-center rounded-full border border-border bg-surface align-middle shadow-xs transition-[background-color,border-color,box-shadow] duration-150 ease-out before:size-2 before:scale-50 before:rounded-full before:bg-primary-foreground before:opacity-0 before:transition-[opacity,transform] before:duration-100 before:ease-out before:content-[''] checked:border-primary checked:bg-primary checked:before:scale-100 checked:before:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none motion-reduce:transition-none motion-reduce:before:transition-none dark:bg-foreground/[0.1] dark:checked:bg-primary aria-invalid:border-danger aria-invalid:checked:bg-danger aria-invalid:focus-visible:outline-danger dark:aria-invalid:checked:bg-danger",
        className
      )}
    />
  )
}
