// generated/solid/radio/radio-group-legend.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type RadioGroupLegendProps = JSX.IntrinsicElements["legend"]

export function RadioGroupLegend(props: RadioGroupLegendProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <legend
      {...rest}
      data-slot="radio-group-legend"
      class={cn("mb-1 text-sm font-medium text-foreground", local.class)}
    >
      {local.children}
    </legend>
  )
}

// packages/components/src/react/radio/radio-group-legend.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type RadioGroupLegendProps = ComponentPropsWithRef<"legend">

export function RadioGroupLegend({ children, className, ...props }: RadioGroupLegendProps) {
  return (
    <legend
      {...props}
      data-slot="radio-group-legend"
      className={cn("mb-1 text-sm font-medium text-foreground", className)}
    >
      {children}
    </legend>
  )
}
