// packages/components/src/solid/pagination/pagination.solid.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type PaginationProps = JSX.IntrinsicElements["nav"]

export function Pagination(props: PaginationProps) {
  const [local, rest] = splitProps(mergeProps({ "aria-label": "Pagination" } as const, props), [
    "aria-label",
    "children",
    "class",
  ])

  return (
    <nav
      {...rest}
      aria-label={local["aria-label"]}
      data-slot="pagination"
      class={cn("min-w-0", local.class)}
    >
      <ul data-slot="pagination-list" class="flex max-w-full items-center justify-center gap-1">
        {local.children}
      </ul>
    </nav>
  )
}

// generated/react/pagination/pagination.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type PaginationProps = ComponentPropsWithRef<"nav">

export function Pagination({
  "aria-label": ariaLabel = "Pagination",
  children,
  className,
  ...props
}: PaginationProps) {
  return (
    <nav
      {...props}
      aria-label={ariaLabel}
      data-slot="pagination"
      className={cn("min-w-0", className)}
    >
      <ul data-slot="pagination-list" className="flex max-w-full items-center justify-center gap-1">
        {children}
      </ul>
    </nav>
  )
}
