// generated/solid/accordion/accordion.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/style"

export type AccordionProps = JSX.IntrinsicElements["div"]

export function Accordion(props: AccordionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])

  return (
    <div {...rest} data-slot="accordion" class={cn("w-full border-y border-border", local.class)}>
      {local.children}
    </div>
  )
}

// generated/react/accordion/accordion.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithoutRef } from "react"

export type AccordionProps = ComponentPropsWithoutRef<"div">

export function Accordion({ children, className, ...props }: AccordionProps) {
  return (
    <div
      {...props}
      data-slot="accordion"
      className={cn("w-full border-y border-border", className)}
    >
      {children}
    </div>
  )
}
