// packages/components/src/solid/popover/popover-description.solid.tsx
import { cn } from "@/lib/style"
import { splitProps, type JSX } from "solid-js"

export type PopoverDescriptionProps = JSX.IntrinsicElements["p"]

export function PopoverDescription(props: PopoverDescriptionProps) {
  const [local, rest] = splitProps(props, ["children", "class"])
  return (
    <p
      {...rest}
      data-slot="popover-description"
      class={cn("m-0 text-xs leading-5 text-muted-foreground", local.class)}
    >
      {local.children}
    </p>
  )
}

// packages/components/src/react/popover/popover-description.react.tsx
import { cn } from "@/lib/style"
import type { ComponentPropsWithRef } from "react"

export type PopoverDescriptionProps = ComponentPropsWithRef<"p">

export function PopoverDescription({ children, className, ...props }: PopoverDescriptionProps) {
  return (
    <p
      {...props}
      data-slot="popover-description"
      className={cn("m-0 text-xs leading-5 text-muted-foreground", className)}
    >
      {children}
    </p>
  )
}
